In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"E:/RetailPulse_Project/data/raw/Online Retail.csv")

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [4]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France
541909,581587,POST,POSTAGE,1,12/9/2011 12:50,18.00,12680.0,France

In [5]:
df.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
471121,576618,16237,SLEEPING CAT ERASERS,1,11/15/2011 17:00,0.42,NaN,United Kingdom
31926,539030,22470,HEART OF WICKER LARGE,12,12/15/2010 14:25,2.95,13089.0,United Kingdom
428873,C573502,22064,PINK DOUGHNUT TRINKET POT,-2,10/31/2011 12:02,1.65,14808.0,United Kingdom
301658,563350,23077,DOUGHNUT LIP GLOSS,3,8/15/2011 14:10,1.25,14498.0,United Kingdom
10073,537224,21143,ANTIQUE GLASS HEART DECORATION,12,12/5/2010 16:24,1.95,13174.0,United Kingdom
457738,575743,23583,LUNCH BAG PAISLEY PARK,30,11/11/2011 10:01,1.65,12757.0,Portugal
251437,559052,84251G,"GREETING CARD, OVERCROWDED POOL.",3,7/5/2011 16:53,0.42,NaN,United Kingdom
391740,570677,23381,PACK OF 12 VINTAGE LEAF TISSUES,12,10/11/2011 15:10,0.39,12836.0,United Kingdom
25203,538356,84029E,RED WOOLLY HOTTIE WHITE HEART.,12,12/10/2010 15:56,3.75,14062.0,United Kingdom
28328,538635,21910,WAY OUT METAL SIGN,1,12/13/2010 13:32,1.65,17303.0,United Kingdom

In [6]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [7]:
df.shape

(541910, 8)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541910 non-null  str
 1   StockCode    541910 non-null  str
 2   Description  540456 non-null  str
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  str
 5   UnitPrice    541910 non-null  float64
 6   CustomerID   406830 non-null  float64
 7   Country      541910 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [9]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541910.000000  541910.000000  406830.000000
mean        9.552234       4.611138   15287.684160
std       218.080957      96.759765    1713.603074
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [10]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541910 non-null  str
 1   StockCode    541910 non-null  str
 2   Description  540456 non-null  str
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[us]
 5   UnitPrice    541910 non-null  float64
 6   CustomerID   406830 non-null  float64
 7   Country      541910 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 33.1 MB

In [12]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [13]:
df.dropna(subset = ["Description","CustomerID"],inplace = True)

In [14]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(5225)

In [16]:
df.drop_duplicates(inplace = True)

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df = df[df["Quantity"]>0]
df = df[df["UnitPrice"]>0]

In [19]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  392693.000000                      392693  392693.000000  392693.000000
mean       13.119671  2011-07-10 19:13:41.156272       3.125952   15287.837224
min         1.000000         2010-12-01 08:26:00       0.001000   12346.000000
25%         2.000000         2011-04-07 11:12:00       1.250000   13955.000000
50%         6.000000         2011-07-31 12:02:00       1.950000   15150.000000
75%        12.000000         2011-10-20 12:53:00       3.750000   16791.000000
max     80995.000000         2011-12-09 12:50:00    8142.750000   18287.000000
std       180.492603                         NaN      22.241820    1713.542421

In [20]:
df = df[~df["InvoiceNo"].str.startswith("C")]

In [21]:
df.to_csv(r"E:\RetailPulse_Project\data\cleaned\cleaned_online_retail_I.csv",index = False)