In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
sheet1 = pd.read_excel(r"E:/RetailPulse_Project/data/raw/online_retail_II.xlsx",sheet_name = "Year 2009-2010")
sheet2 = pd.read_excel(r"E:/RetailPulse_Project/data/raw/online_retail_II.xlsx",sheet_name = "Year 2010-2011")

df = pd.concat([sheet1,sheet2],ignore_index = True)
df.to_csv(
    r"E:\RetailPulse_Project\data\raw\online_retail_II_full.csv",
    index=False
)

In [4]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [6]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [14]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [15]:
df.rename(columns={"Invoice": "InvoiceNo","Price": "UnitPrice","Customer ID": "CustomerID"}, inplace=True)

In [16]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB

In [9]:
df.describe()

           Quantity                 InvoiceDate         Price    Customer ID
count  1.067371e+06                     1067371  1.067371e+06  824364.000000
mean   9.938898e+00  2011-01-02 21:13:55.394029  4.649388e+00   15324.638504
min   -8.099500e+04         2009-12-01 07:45:00 -5.359436e+04   12346.000000
25%    1.000000e+00         2010-07-09 09:46:00  1.250000e+00   13975.000000
50%    3.000000e+00         2010-12-07 15:28:00  2.100000e+00   15255.000000
75%    1.000000e+01         2011-07-22 10:23:00  4.150000e+00   16797.000000
max    8.099500e+04         2011-12-09 12:50:00  3.897000e+04   18287.000000
std    1.727058e+02                         NaN  1.235531e+02    1697.464450

In [10]:
df.shape

(1067371, 8)

In [18]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     243007
Country             0
dtype: int64

In [19]:
df.dropna(subset = ["Description","CustomerID"],inplace = True)

In [20]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(26479)

In [24]:
df.drop_duplicates(inplace = True)

In [25]:
df.duplicated().sum()

np.int64(0)

In [27]:
df = df[df["Quantity"]>0]
df = df[df["UnitPrice"]>0]

In [29]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  779425.000000                      779425  779425.000000  779425.000000
mean       13.489370  2011-01-03 01:44:42.593476       3.218488   15320.360461
min         1.000000         2009-12-01 07:45:00       0.001000   12346.000000
25%         2.000000         2010-07-02 14:39:00       1.250000   13971.000000
50%         6.000000         2010-12-02 14:09:00       1.950000   15247.000000
75%        12.000000         2011-08-01 13:44:00       3.750000   16794.000000
max     80995.000000         2011-12-09 12:50:00   10953.500000   18287.000000
std       145.855814                         NaN      29.676140    1695.692775

In [28]:
df[df["InvoiceNo"].astype(str).str.startswith("C")].shape

(0, 8)

In [30]:
df = df[~df["InvoiceNo"].astype(str).str.startswith("C")]

In [31]:
df[df["InvoiceNo"].astype(str).str.startswith("C")].shape

(0, 8)

In [32]:
df.to_csv(r"E:\RetailPulse_Project\data\cleaned\cleaned_online_retail_II.csv",index = False)